// <auto-generated />
using Shares.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Shares.Migrations
{
    [DbContext(typeof(SqlServerDbContext))]
    partial class SqlServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shares.Modelo.Seguridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Seguridad");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "abc1",
                            Roles = "User",
                            TenantId = 0,
                            UserName = "admin1"
                        },
                        new
                        {
                            Id = 2,
                            Password = "abc2",
                            Roles = "User",
                            TenantId = 0,
                            UserName = "admin2"
                        },
                        new
                        {
                            Id = 3,
                            Password = "abc3",
                            Roles = "User",
                            TenantId = 0,
                            UserName = "admin3"
                        },
                        new
                        {
                            Id = 4,
                            Password = "abc4",
                            Roles = "User",
                            TenantId = 1,
                            UserName = "admin4"
                        },
                        new
                        {
                            Id = 5,
                            Password = "abc5",
                            Roles = "User",
                            TenantId = 1,
                            UserName = "admin5"
                        },
                        new
                        {
                            Id = 6,
                            Password = "abc6",
                            Roles = "User",
                            TenantId = 1,
                            UserName = "admin6"
                        },
                        new
                        {
                            Id = 7,
                            Password = "abc7",
                            Roles = "User",
                            TenantId = 2,
                            UserName = "admin7"
                        },
                        new
                        {
                            Id = 8,
                            Password = "abc8",
                            Roles = "User",
                            TenantId = 2,
                            UserName = "admin8"
                        },
                        new
                        {
                            Id = 9,
                            Password = "abc9",
                            Roles = "User",
                            TenantId = 2,
                            UserName = "admin9"
                        });
                });

            modelBuilder.Entity("Shares.Modelo.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contexto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "0001",
                            Contexto = "SqlServer",
                            Password = "abc 11",
                            TenantId = 0,
                            UserName = "Usuario1"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "0002",
                            Contexto = "SqlServer",
                            Password = "abc 22",
                            TenantId = 1,
                            UserName = "Usuario2"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "0003",
                            Contexto = "SqlServer",
                            Password = "abc 33",
                            TenantId = 2,
                            UserName = "Usuario3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
