// <auto-generated />
using Shares.Genericos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Shares.Migrations.SqLiteDb
{
    [DbContext(typeof(SqLiteDbContext))]
    partial class SqLiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Shares.Modelo.Seguridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Seguridad");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "abc1",
                            Roles = "Admin",
                            TenantId = 0,
                            UserName = "admin1"
                        },
                        new
                        {
                            Id = 2,
                            Password = "abc2",
                            Roles = "Admin",
                            TenantId = 0,
                            UserName = "admin2"
                        },
                        new
                        {
                            Id = 3,
                            Password = "abc3",
                            Roles = "Admin",
                            TenantId = 0,
                            UserName = "admin3"
                        },
                        new
                        {
                            Id = 4,
                            Password = "abc4",
                            Roles = "Admin",
                            TenantId = 1,
                            UserName = "admin4"
                        },
                        new
                        {
                            Id = 5,
                            Password = "abc5",
                            Roles = "Admin",
                            TenantId = 1,
                            UserName = "admin5"
                        },
                        new
                        {
                            Id = 6,
                            Password = "abc6",
                            Roles = "Admin",
                            TenantId = 1,
                            UserName = "admin6"
                        },
                        new
                        {
                            Id = 7,
                            Password = "abc7",
                            Roles = "Admin",
                            TenantId = 2,
                            UserName = "admin7"
                        },
                        new
                        {
                            Id = 8,
                            Password = "abc8",
                            Roles = "Admin",
                            TenantId = 2,
                            UserName = "admin8"
                        },
                        new
                        {
                            Id = 9,
                            Password = "abc9",
                            Roles = "Admin",
                            TenantId = 2,
                            UserName = "admin9"
                        });
                });

            modelBuilder.Entity("Shares.Modelo.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contexto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "0001",
                            Contexto = "SqLite",
                            Password = "abc 11",
                            TenantId = 0,
                            UserName = "Usuario1"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "0002",
                            Contexto = "SqLite",
                            Password = "abc 22",
                            TenantId = 1,
                            UserName = "Usuario2"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "0003",
                            Contexto = "SqLite",
                            Password = "abc 33",
                            TenantId = 2,
                            UserName = "Usuario3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
