// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shares.Contextos;

#nullable disable

namespace Shares.Migrations
{
    [DbContext(typeof(SqlServerDbContext))]
    [Migration("20251218111755_nueva")]
    partial class nueva
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorSeguridad2026.Data.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contexto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "0001",
                            Contexto = "SqlServer",
                            Password = "abc 11",
                            TenantId = 0,
                            UserName = "Usuario1"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "0002",
                            Contexto = "SqlServer",
                            Password = "abc 22",
                            TenantId = 1,
                            UserName = "Usuario2"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "0003",
                            Contexto = "SqlServer",
                            Password = "abc 33",
                            TenantId = 2,
                            UserName = "Usuario3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
